version: '3.8'

services:
  app:
    image: ${APP_IMAGE}
    container_name: perf-lab-app
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.1'
          memory: 128M
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    container_name: perf-lab-nginx
    ports:
      - "9999:9999"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app
    restart: unless-stopped

networks:
  default:
    name: perf-lab-network