apiVersion: 1

datasources:
  - name: InfluxDB-K6
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    database: k6
    user: k6
    secureJsonData:
      password: k6password
    isDefault: false
    jsonData:
      httpMode: GET