services:
  influxdb:
    image: influxdb:1.8
    container_name: perf-lab-influxdb
    ports:
      - "8086:8086"
    environment:
      - INFLUXDB_DB=k6
      - INFLUXDB_USER=k6
      - INFLUXDB_USER_PASSWORD=k6password
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=admin
    volumes:
      - influxdb_data:/var/lib/influxdb
      - ./influxdb/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    container_name: perf-lab-grafana
    ports:
      - "3001:3000"
    volumes:
      - ./grafana/datasources:/etc/grafana/provisioning/datasources:ro
      - ./grafana/dashboards:/etc/grafana/provisioning/dashboards:ro
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    depends_on:
      - influxdb
    restart: unless-stopped

  k6:
    image: grafana/k6:latest
    container_name: perf-lab-k6
    volumes:
      - ../k6:/scripts:ro
      - ../results:/shared/results:rw
    environment:
      - K6_INFLUXDB_URL=http://influxdb:8086
      - K6_INFLUXDB_DB=k6
      - K6_INFLUXDB_USERNAME=k6
      - K6_INFLUXDB_PASSWORD=k6password
      - RESULTS_DIR=/shared/results
    depends_on:
      - influxdb
    profiles:
      - testing
    networks:
      - default

volumes:
  influxdb_data:

networks:
  default:
    name: perf-lab-network
    external: true